# https://artifacthub.io/packages/helm/bitnami/mongodb
global:
  storageClass: jelastic-dynamic-volume
image:
  tag: 5.0.8-debian-10-r10
architecture: replicaset
useStatefulSet: true
replicaCount: 1
auth:
  enabled: false
service:
  type: ClusterIP
  portName: mongodb
  ports:
    mongodb: 27017
persistence:
  enabled: true
arbiter:
  enabled: false
