# https://github.com/bitnami/charts/tree/master/bitnami/postgresql
global:
  storageClass: jelastic-dynamic-volume
image:
  tag: 14.3.0-debian-11-r0
architecture: standalone
primary:
  initdb:
    scripts:
      create_hasura_db.sh: |
        #! /bin/sh
        
        psql -U ${POSTGRESQL_USERNAME} <<-EOSQL
          CREATE USER HASURA_DB_USERNAME PASSWORD 'HASURA_DB_PASSWORD';
          CREATE DATABASE HASURA_DB_NAME OWNER HASURA_DB_USERNAME ENCODING 'utf-8' TEMPLATE template0;
        EOSQL
        
        psql -U ${POSTGRESQL_USERNAME} -d HASURA_DB_NAME <<-EOSQL
          ALTER SCHEMA public OWNER TO HASURA_DB_USERNAME;
          CREATE EXTENSION IF NOT EXISTS pgcrypto;
          CREATE EXTENSION IF NOT EXISTS citext;
          CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
          CREATE SCHEMA IF NOT EXISTS hdb_catalog;
          ALTER SCHEMA hdb_catalog OWNER TO HASURA_DB_USERNAME;
          CREATE SCHEMA IF NOT EXISTS hdb_views;
          ALTER SCHEMA hdb_views OWNER TO HASURA_DB_USERNAME;
          GRANT SELECT ON ALL TABLES IN SCHEMA information_schema TO HASURA_DB_USERNAME;
          GRANT SELECT ON ALL TABLES IN SCHEMA pg_catalog TO HASURA_DB_USERNAME;
          GRANT USAGE ON SCHEMA public TO HASURA_DB_USERNAME;
          GRANT ALL ON ALL TABLES IN SCHEMA public TO HASURA_DB_USERNAME;
          GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO HASURA_DB_USERNAME;
          GRANT ALL ON ALL FUNCTIONS IN SCHEMA public TO HASURA_DB_USERNAME;
        EOSQL
      create_fusionauth_db.sh: |
        #! /bin/sh
        
        psql -U ${POSTGRESQL_USERNAME} <<-EOSQL
          CREATE USER FUSIONAUTH_DB_USERNAME PASSWORD 'FUSIONAUTH_DB_PASSWORD';
          CREATE DATABASE FUSIONAUTH_DB_NAME ENCODING 'UTF-8' TEMPLATE template0;
        EOSQL