#! /bin/sh

export PGPASSWORD=${DATABASE_ADMIN_PASSWORD}
psql -h "${DATABASE_HOSTNAME}" -p "${DATABASE_PORT}" -U "${DATABASE_ADMIN_USER}" -d "${HASURA_DB_NAME}" <<-EOSQL
  ALTER SCHEMA public OWNER TO ${HASURA_DB_USERNAME};
  CREATE EXTENSION IF NOT EXISTS pgcrypto;
  CREATE EXTENSION IF NOT EXISTS citext;
  CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
  CREATE SCHEMA IF NOT EXISTS hdb_catalog;
  ALTER SCHEMA hdb_catalog OWNER TO ${HASURA_DB_USERNAME};
  CREATE SCHEMA IF NOT EXISTS hdb_views;
  ALTER SCHEMA hdb_views OWNER TO ${HASURA_DB_USERNAME};
  GRANT SELECT ON ALL TABLES IN SCHEMA information_schema TO ${HASURA_DB_USERNAME};
  GRANT SELECT ON ALL TABLES IN SCHEMA pg_catalog TO ${HASURA_DB_USERNAME};
  GRANT USAGE ON SCHEMA public TO ${HASURA_DB_USERNAME};
  GRANT ALL ON ALL TABLES IN SCHEMA public TO ${HASURA_DB_USERNAME};
  GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO ${HASURA_DB_USERNAME};
  GRANT ALL ON ALL FUNCTIONS IN SCHEMA public TO ${HASURA_DB_USERNAME};
EOSQL