type: update
name: Jelasticozor Backend Cluster SSL
baseUrl: https://raw.githubusercontent.com/jelasticozor/deployment-infrastructure/main

onInstall:
  - cmd[${nodes.k8sm.master.id}]: |-
      wget ${baseUrl}/kubernetes/api-ingress.yaml -O api-ingress.yaml
      sed -i s/FQDN/${env.domain}/g api-ingress.yaml
      kubectl apply -f api-ingress.yaml
